AWSTemplateFormatVersion: '2010-09-09'
Description: Membership Attributes service
Parameters:
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
  Stage:
    Description: Environment name
    Type: String
    Default: PROD
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.small
    AllowedValues:
    - t2.micro
    - t2.small
    - t2.medium
    - m3.medium
    - m3.large
    - m3.xlarge
    - m3.2xlarge
    - c3.large
    - c3.xlarge
    - c3.2xlarge
    - c3.4xlarge
    - c3.8xlarge
    - g2.2xlarge
    - r3.large
    - r3.xlarge
    - r3.2xlarge
    - r3.4xlarge
    - r3.8xlarge
    - i2.xlarge
    - i2.2xlarge
    - i2.4xlarge
    - i2.8xlarge
    - hs1.8xlarge
    ConstraintDescription: must be a valid EC2 instance type.
  MaxInstances:
    Description: Maximum number of instances. This should be (at least) double the
      desired capacity.
    Type: Number
    Default: 6
  MinInstances:
    Description: Minimum number of instances
    Type: Number
    Default: 3
  VpcId:
    Description: ID of the VPC onto which to launch the application
    Type: AWS::EC2::VPC::Id
    Default: vpc-e6e00183
  VpcSubnets:
    Description: Subnets to use in VPC
    Type: CommaDelimitedList
    Default: subnet-cb91ae8d,subnet-a7b74ac2,subnet-179e8063
  AmiId:
    Description: Custom AMI to use for instances
    Type: String
  VulnerabilityScanningSecurityGroup:
    Description: Security group that grants access to the account's Vulnerability Scanner
    Type: AWS::EC2::SecurityGroup::Id
  LoggingKinesisStream:
    Description: Kinesis stream id to send logging to e.g. elk-stack-ElkKinesisStream-12345
    Type: String
  LoggingPolicy:
    Description: Policy needed to access the kinesis stream
    Type: String
Mappings:
  StageVariables:
    PROD:
      NotificationAlarmPeriod: 1200
      InstanceName: PROD:membership-attribute-service
      DynamoDBTable: arn:aws:dynamodb:*:*:table/MembershipAttributes-PROD
      DynamoDBTableTestUsers: arn:aws:dynamodb:*:*:table/MembershipAttributes-UAT
      DynamoDBBehaviourTable: arn:aws:dynamodb:*:*:table/MembershipBehaviour-PROD
      DynamoDBBehaviourTableTestUsers: arn:aws:dynamodb:*:*:table/MembershipBehaviour-UAT
      GiraffeTopic: giraffe
      SSLCertificate: arn:aws:iam::865473395570:server-certificate/members-data-api.theguardian.com

    CODE:
      NotificationAlarmPeriod: 1200
      InstanceName: CODE:membership-attribute-service
      DynamoDBTable: arn:aws:dynamodb:*:*:table/MembershipAttributes-UAT
      DynamoDBTableTestUsers: arn:aws:dynamodb:*:*:table/MembershipAttributes-UAT
      DynamoDBBehaviourTable: arn:aws:dynamodb:*:*:table/MembershipBehaviour-UAT
      DynamoDBBehaviourTableTestUsers: arn:aws:dynamodb:*:*:table/MembershipBehaviour-UAT
      GiraffeTopic: giraffe-code

Resources:
  MembershipRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Statement:
          - Action: s3:GetObject
            Resource: arn:aws:s3:::gu-membership-*/*
            Effect: Allow
          - Action: s3:GetObject
            Resource: arn:aws:s3:::members-data-api-private/*
            Effect: Allow
          - Action: ec2:DescribeTags
            Resource: "*"
            Effect: Allow
          - Effect: Allow
            Action:
            - sns:Publish
            Resource:
              Ref: TopicGiraffe
          - Action:
            - logs:*
            Resource:
            - arn:aws:logs:*:*:*
            Effect: Allow
          - Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
            Resource:
              Fn::FindInMap: [ StageVariables, { Ref: Stage }, DynamoDBTable ]
            Effect: Allow
          - Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
            Resource:
              Fn::FindInMap: [ StageVariables, { Ref: Stage }, DynamoDBTableTestUsers ]
            Effect: Allow
          - Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
            Resource:
              Fn::FindInMap: [ StageVariables, { Ref: Stage }, DynamoDBBehaviourTable ]
            Effect: Allow
          - Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
            Resource:
              Fn::FindInMap: [ StageVariables, { Ref: Stage }, DynamoDBBehaviourTableTestUsers ]
            Effect: Allow
          - Action:
            - cloudwatch:*
            - logs:*
            Resource: "*"
            Effect: Allow
      ManagedPolicyArns:
      - !Ref 'LoggingPolicy'
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - Ref: MembershipRole
  GuardianAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH access from Guardian network
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 77.91.248.0/21
  LoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Listeners:
      - LoadBalancerPort: '443'
        InstancePort: '9000'
        Protocol: HTTPS
        SSLCertificateId:
          Fn::FindInMap: [ StageVariables, { Ref: Stage }, SSLCertificate ]
      ConnectionDrainingPolicy:
        Enabled: 'true'
        Timeout: '60'
      CrossZone: 'true'
      HealthCheck:
        Target: HTTP:9000/healthcheck
        HealthyThreshold: '2'
        UnhealthyThreshold: '3'
        Interval: '10'
        Timeout: '5'
      Subnets:
        Ref: VpcSubnets
      SecurityGroups:
      - Ref: LoadBalancerSecurityGroup
  AutoscalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        Fn::GetAZs: ''
      LaunchConfigurationName:
        Ref: LaunchConfig
      MinSize:
        Ref: MinInstances
      MaxSize:
        Ref: MaxInstances
      HealthCheckType: ELB
      HealthCheckGracePeriod: 400
      LoadBalancerNames:
      - Ref: LoadBalancer
      Tags:
      - Key: Stage
        Value:
          Ref: Stage
        PropagateAtLaunch: 'true'
      - Key: Name
        Value:
          Fn::FindInMap: [ StageVariables, { Ref: Stage }, InstanceName ]
        PropagateAtLaunch: 'true'
      - Key: Stack
        Value: membership
        PropagateAtLaunch: 'true'
      - Key: App
        Value: membership-attribute-service
        PropagateAtLaunch: 'true'
      - Key: Role
        Value: membership-attribute-service
        PropagateAtLaunch: 'true'
      - Key: Mainclass
        Value: membership-attribute-service
        PropagateAtLaunch: 'true'
      VPCZoneIdentifier:
        Ref: VpcSubnets
  LaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      KeyName:
        Ref: KeyName
      ImageId:
        Ref: AmiId
      SecurityGroups:
      - Ref: InstanceSecurityGroup
      - Ref: GuardianAccessSecurityGroup
      - Ref: VulnerabilityScanningSecurityGroup
      InstanceType:
        Ref: InstanceType
      AssociatePublicIpAddress: 'True'
      IamInstanceProfile:
        Ref: InstanceProfile
      UserData:
        "Fn::Base64":
          !Sub
            - |
              #!/bin/bash -ev
              aws s3 cp s3://gu-membership-attribute-service-dist/set-ssh-keys.sh .
              chmod +x set-ssh-keys.sh
              ./set-ssh-keys.sh
              CONF_DIR=/etc/membership-attribute-service
              aws s3 cp s3://gu-membership-attribute-service-dist/membership/${Stage}/membership-attribute-service/membership-attribute-service_1.0-SNAPSHOT_all.deb /tmp
              dpkg -i /tmp/membership-attribute-service_1.0-SNAPSHOT_all.deb
              mkdir -p /etc/gu
              aws --region ${AWS::Region} s3 cp s3://members-data-api-private/${Stage}/members-data-api.private.conf /etc/gu
              chown membership-attribute-service /etc/gu/members-data-api.private.conf
              chmod 0600 /etc/gu/members-data-api.private.conf

              cat <<EOF >>/etc/gu/members-data-api.private.conf
              param.logstash {
                stream="${LoggingKinesisStream}"
                streamRegion="${AWS::Region}"
              }
              EOF

              wget https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py
              sed -i -e "s/__DATE/$(date +%F)/" -e 's/__STAGE/${Stage}/' $CONF_DIR/logger.conf
              python awslogs-agent-setup.py -nr ${AWS::Region} -c $CONF_DIR/logger.conf
              systemctl enable awslogs
              systemctl start awslogs
            - {}
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VpcId
      GroupDescription: Open up HTTPS access to load balancer
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '443'
        ToPort: '443'
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: '9000'
        ToPort: '9000'
        CidrIp: 0.0.0.0/0
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VpcId
      GroupDescription: Open up HTTP access to load balancer
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '9000'
        ToPort: '9000'
        SourceSecurityGroupId:
          Ref: LoadBalancerSecurityGroup
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: '443'
        ToPort: '443'
        CidrIp: 0.0.0.0/0
  TopicGiraffe:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Fn::FindInMap: [ StageVariables, { Ref: Stage }, GiraffeTopic ]
Outputs:
  LoadBalancerUrl:
    Value:
      Fn::GetAtt:
      - LoadBalancer
      - DNSName
