name: Scala Steward PR handling

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Scala Steward PR
    if: github.actor == 'scala-steward'
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout repo
      uses: actions/checkout@v3
    - 
      uses: guardian/setup-scala@v1
    - 
      name: Run tests
      run: sbt test
      
