# This action runs snyk monitor on every push to main
name: Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      DEBUG: true
      ORG: guardian-portfolio-and-platform
      SKIP_NODE: true
      PROJECT_FILE: build.sbt
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
